"""Unsupervised topic discovery and keyword extraction.

Approach: TF-IDF vectors of each conversation's customer text, factorised with
Non-negative Matrix Factorization (NMF). NMF expresses every conversation as a
non-negative mix of ``k`` topics, and every topic as a weighted set of terms.
Each conversation is assigned its dominant topic, and each topic is named after
its highest-weighted terms.

This is *unsupervised* — no labels are used — so topic names are keyword
summaries generated by the model, not ground truth. NMF was chosen over
K-Means because, on short support messages, K-Means tended to put most
conversations into one catch-all cluster, while NMF produced more balanced and
interpretable topics.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from sklearn.decomposition import NMF
from sklearn.feature_extraction.text import TfidfVectorizer

from src.preprocessing import STOPWORDS, TOKEN_PATTERN, normalize_text

UNASSIGNED_TOPIC = -1


def build_vectorizer(n_docs: int) -> TfidfVectorizer:
    """TF-IDF settings shared by topic modelling and keyword extraction."""
    return TfidfVectorizer(
        preprocessor=normalize_text,
        stop_words=sorted(STOPWORDS),
        token_pattern=TOKEN_PATTERN,
        ngram_range=(1, 2),
        min_df=2 if n_docs >= 20 else 1,
        max_df=0.5 if n_docs >= 20 else 1.0,
        sublinear_tf=True,
    )


def _distinct_terms(ranked_terms: list[str], n: int) -> list[str]:
    """Pick up to ``n`` terms, skipping ones already covered by a chosen term.

    Avoids names like "charged twice / charged / twice".
    """
    chosen: list[str] = []
    for term in ranked_terms:
        words = set(term.split())
        if any(words <= set(c.split()) or set(c.split()) <= words for c in chosen):
            continue
        chosen.append(term)
        if len(chosen) == n:
            break
    return chosen


@dataclass
class TopicModel:
    """A fitted topic model plus per-document assignments."""

    vectorizer: TfidfVectorizer
    nmf: NMF
    labels: np.ndarray  # dominant topic per document, or UNASSIGNED_TOPIC
    weights: np.ndarray  # document-topic matrix
    topic_terms: dict[int, list[str]]  # top terms per topic (ranked)

    def topic_name(self, topic_id: int, n_terms: int = 3) -> str:
        if topic_id == UNASSIGNED_TOPIC:
            return "Unassigned"
        terms = _distinct_terms(self.topic_terms.get(topic_id, []), n_terms)
        return " / ".join(terms) if terms else f"Topic {topic_id}"

    @property
    def topic_names(self) -> dict[int, str]:
        names = {tid: self.topic_name(tid) for tid in self.topic_terms}
        names[UNASSIGNED_TOPIC] = "Unassigned"
        return names

    def assign(self, text: str) -> int:
        """Assign a text to its dominant topic (``UNASSIGNED_TOPIC`` if no known terms)."""
        weights = self.nmf.transform(self.vectorizer.transform([text]))[0]
        return int(np.argmax(weights)) if weights.sum() > 0 else UNASSIGNED_TOPIC

    def keywords(self, text: str, top_n: int = 8) -> list[str]:
        """Highest-weighted TF-IDF terms of ``text`` under the fitted vocabulary."""
        vector = self.vectorizer.transform([text]).toarray()[0]
        order = np.argsort(vector)[::-1]
        terms = self.vectorizer.get_feature_names_out()
        ranked = [str(terms[i]) for i in order if vector[i] > 0]
        return _distinct_terms(ranked, top_n)


def fit_topics(texts: list[str], n_topics: int = 8, random_state: int = 42, n_terms: int = 8) -> TopicModel:
    """Fit TF-IDF + NMF on ``texts``.

    ``n_topics`` is clamped to what the data can support.

    Raises:
        ValueError: if ``texts`` is empty or produces an empty vocabulary.
    """
    if not texts:
        raise ValueError("Cannot fit topics on an empty list of texts.")
    vectorizer = build_vectorizer(len(texts))
    matrix = vectorizer.fit_transform(texts)  # raises ValueError on empty vocabulary
    k = max(1, min(n_topics, matrix.shape[0], matrix.shape[1]))

    # NNDSVD initialisation needs k < min(n_docs, n_terms); tiny corpora fall back to random init.
    init = "nndsvda" if k < min(matrix.shape) else "random"
    nmf = NMF(n_components=k, init=init, random_state=random_state, max_iter=500)
    with np.errstate(invalid="ignore"):  # tiny corpora can reconstruct exactly -> sqrt(-0.0) noise
        weights = nmf.fit_transform(matrix)
    labels = np.where(weights.sum(axis=1) > 0, weights.argmax(axis=1), UNASSIGNED_TOPIC)

    terms = vectorizer.get_feature_names_out()
    topic_terms = {
        topic_id: [str(terms[i]) for i in np.argsort(component)[::-1][:n_terms] if component[i] > 0]
        for topic_id, component in enumerate(nmf.components_)
    }
    return TopicModel(vectorizer=vectorizer, nmf=nmf, labels=labels, weights=weights, topic_terms=topic_terms)


def corpus_keywords(texts: list[str], top_n: int = 15) -> list[tuple[str, float]]:
    """Top terms across a set of texts, ranked by summed TF-IDF weight."""
    texts = [t for t in texts if t and t.strip()]
    if not texts:
        return []
    vectorizer = build_vectorizer(len(texts))
    try:
        matrix = vectorizer.fit_transform(texts)
    except ValueError:  # empty vocabulary after stop-word removal
        return []
    weights = np.asarray(matrix.sum(axis=0)).ravel()
    order = np.argsort(weights)[::-1]
    terms = vectorizer.get_feature_names_out()
    ranked = [str(terms[i]) for i in order]
    keep = set(_distinct_terms(ranked, top_n))
    return [(str(terms[i]), round(float(weights[i]), 3)) for i in order if str(terms[i]) in keep][:top_n]
