[theme]
base = "light"
primaryColor = "#2a78d6"
backgroundColor = "#fcfcfb"
secondaryBackgroundColor = "#f3f2ef"
textColor = "#0b0b0b"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
